name: Arkle & Company
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4847609084099531
title: Arkle & Company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2796837706118822
  lightness: 0.7339172535575926
  saturation: 0.6047202171757817
  rhythmicContrast: 0.04767435719259083
purpose: []
