name: Arkle & Company
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4847609084099531
title: Arkle & Company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#732f2f'
    - '#a97f7f'
    - '#007900'
    - '#00007c'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
