typography_spectrum: 0.4847609084099531
color:
  brandColors:
    - '#ffffff'
    - '#732f2f'
    - '#a97f7f'
    - '#007900'
    - '#00007c'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24225
analytics:
  google: null
  facebook: null
  twitter: null
name: Arkle & Company
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Arkle & Company
description: Imagine what you will know tomorrow...
purpose: []
